# Generated by Django 4.1.5 on 2023-01-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Enter author name')),
                ('contact', models.CharField(max_length=30, verbose_name='Enter contact number')),
                ('email', models.EmailField(max_length=30, verbose_name='Enter email id')),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Author_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Enter author category name')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Enter blog name')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Enter tag name')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Enter title name')),
                ('content', models.CharField(max_length=1000, verbose_name='Enter contact number')),
                ('upload_date', models.DateTimeField(max_length=50, verbose_name='Enter upload date and time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blog_category')),
                ('tags', models.ManyToManyField(to='main.tags')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='author_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author_category'),
        ),
    ]
